use NIIT;
desc Questions;
insert into Questions values("Q001","EM001","Instructor knowledgeable and able to handle all your queries");
insert into Questions values("Q002","EM001","All the topics in a particular course handled by the trainer without any gaps or slippages");
insert into Questions values("Q003","EM002","The course materials presentation, handson, etc. refered during the training are relevant and useful.");
insert into Questions values("Q004","EM002","The Hands on session adequate enough to grasp the understanding of the topi");
insert into Questions values("Q005","EM002","The reference materials suggested for each module are adequate.");
insert into Questions values("Q006","EM003","Knowledge and skills presented in this training are applicatible at your work");
insert into Questions values("Q007","EM003","This training increases my proficiency level");
insert into Questions values("Q008","EM004","The physical environment e.g. classroom space, air-conditioning was conducive to learning.");
insert into Questions values("Q009","EM004","The software/hardware environment provided was sufficient for the purpose of the training.");
insert into Questions values("Q010","EM005","This training will improve your job performance.");
insert into Questions values("Q011","EM005","This training align with the business priorities and goals.");
insert into Questions values("Q012","TM001","Participants were receptive and had attitude towards learning.");